#!/bin/sh

bdir=`mvn help:evaluate -o -Dexpression=project.build.directory | grep -v '[INFO]'`

rm -rf ${bdir}/jacore
rm -f ${bdir}/test-log4j.log
rm -rf ${bdir}/cglib

j7 mvn -o test "$@" || exit

dot -T png ${bdir}/jacore/test-module.dot > ${bdir}/jacore/test-module.png
